on:
  push:
    branches-ignore: [main]

name: Test

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: docker
    container:
      image: forge.macopla.com/homelab/packer/packer-ci:latest
      credentials:
        username: yoann
        password: ${{ secrets.CI_PACKER_PULL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
