on: [push, pull_request]
jobs:
  pre-commit:
    runs-on: nix
    env:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    steps:
      - run: nix profile install nixpkgs#nodejs
      - uses: actions/checkout@v6
      - run: nix develop -c pre-commit run --all-files --show-diff-on-failure
